services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
      - ./shared:/app/shared
      - uploads:/app/uploads
      - ./db:/app/db
    environment:
      - PYTHONPATH=/app/src
      - ENVIRONMENT=development
      - PORT=${BACKEND_PORT}
    env_file:
      - .env
      - .env.local
    restart: unless-stopped
    command: uv run python main.py

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - ./shared:/app/shared
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=${FRONTEND_PORT}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
    env_file:
      - .env
      - .env.local
    depends_on:
      - backend
    restart: unless-stopped
    command: npm run dev

volumes:
  uploads:
  frontend_node_modules:

networks:
  default:
    name: agent_network