[project]
name = "agent"
version = "0.1.0"
description = "Initial setup"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.59.0",
    "ipykernel>=6.30.0",
    "openai>=1.97.1",
    "pydantic>=2.11.7",
    "sqlalchemy>=2.0.41",
]
